# Generated by Django 4.2.2 on 2023-06-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=20)),
                ('Nationality', models.CharField(max_length=25)),
                ('Mobile', models.IntegerField()),
                ('Password', models.CharField(max_length=10)),
                ('Roles', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('admin', 'Admin'), ('editor', 'Editor')], max_length=10)),
            ],
        ),
    ]
